server:
  port: 8080
  
spring:
  application:
    name: spring-data-mongodb-example
  data:
    mongodb:
      host: '${MONGO_HOST}'
      database: '${MONGO_DB}'
      port: 27017
      username: '${MONGO_USERNAME}'
      password: '${MONGO_PASSWORD}'